login_app/urls.py
# -*- coding: utf-8 -*-
# @Author: sylvain
# @Date:   2019-07-08 14:58:03
# @Last Modified by:   Sylvain-Yu
# @Last Modified time: 2019-07-17 11:07:08
from django.urls import path
from . import views

app_name = 'login_app'
#start with "accounts/"
urlpatterns = [
    path('', views.reindex, name='reindex'),
    path('index/',views.index, name = 'index'),
    path('login/',views.login, name = 'login'),
    path('register/',views.register, name = 'register'),
    path('logout/',views.logout, name = 'logout'),
]

magelec_web/urls.py
from django.contrib import admin
from django.urls import path, include
from login_app import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.reindex),
    path('index/',views.reindex),
    path('admin/', admin.site.urls),
    path('account/',include('login_app.urls')),
    path('test/',include('test_app.urls')),
] + static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)

test_app/urls.py
# -*- coding: utf-8 -*-
# @Author: Sylvain-Yu
# @Date:   2019-07-12 17:13:07
# @Last Modified by:   Sylvain-Yu
# @Last Modified time: 2019-08-30 08:54:07
from django.urls import path
from . import views
app_name ='test_app'

urlpatterns = [
    path('dataview/', views.dataview, name='dataview'),
    path('highspeed/',views.highspeed, name ='highspeed'),
    path('basic/',views.basic,name = 'basic'),
    path('search/',views.search,name = 'search'),
    path('motor_logout/',views.motor_logout,name ='motor_logout'),
    path('index/',views.index,name='index'),
    path('motor_login/',views.motor_login,name = 'motor_login'),
    path('currentvstorque/',views.currentvstorque,name = 'currentvstorque'),
    path('shortcircuit/',views.shortcircuit,name = 'shortcircuit'),
    path('insulation/',views.insulation,name = 'insulation'),
    path('continuous/',views.continuous, name = 'continuous'),
    path('bemf/',views.bemf, name = 'bemf'),
    path('calibrate/',views.calibrate, name = 'calibrate'),
    path('gamma/',views.gamma, name = 'gamma'),
    path('efficiency/',views.efficiency, name ='efficiency'),

]

test_app/models.py
from django.db import models
from login_app.models import User
# Create your models here.


class MotorInfo(models.Model):
    motor_PN = models.CharField(max_length=32)
    motor_model = models.CharField(max_length=32)
    motor_code = models.CharField(max_length=32)
    tester_list = (('Leon Chen', '陈晓文'),
                   ('Tiegen Ji', '季铁根'),
                   ('Sylvain Yu', '郁松林'),
                   ('Jiliang Hong', '洪继良'),
                   ('Charles Li', '李文昌'),
                   ('Brant Miao', '苗强'),
                   ('others', '其他'),
                   )
    tester1 = models.CharField(max_length=32, choices=tester_list)
    tester2 = models.CharField(max_length=32, choices=tester_list)
    ambient_temperature = models.FloatField()
    ambient_humidity = models.FloatField()
    motor_poles = models.IntegerField()
    resolver_poles = models.IntegerField()
    inverter_type_list = (('RMS PM250DZ', 'RMS PM250DZ'),
                          ('RMS PM100', 'RMS PM100'),
                          ('EMSISO EM500', 'EMSISO EM500'),
                          ('EMSISO EM100', 'EMSISO EM100'),
                          ('EMSISO EM200', 'EMSISO EM200'),
                          ('EMSISO EM250', 'EMSISO EM250'),
                          ('unknown', '其他'),
                          )
    inverter_type = models.CharField(max_length=32, choices=inverter_type_list)
    inverter_serial = models.CharField(max_length=32)
    phase_connection_list = (('UVW to ABC', 'UVW to ABC'),
                             ('UWV to ABC', 'UWV to ABC'),
                             )
    phase_connection = models.CharField(
        max_length=32, choices=phase_connection_list)
    motor_type_options_eeprom = models.IntegerField()
    forward_direction_list = (('clockwise', '顺时针'),
                              ('anti-clockwise', '逆时针'),
                              )
    forward_direction = models.CharField(
        max_length=32, choices=forward_direction_list)
    comment = models.CharField(max_length=128, null=True, blank=True)
    c_time = models.DateTimeField(auto_now_add=True)
    modify_time = models.DateTimeField(auto_now=True)
    recorder = models.ForeignKey(User,on_delete = models.SET_NULL,null= True)

    class Meta:
        ordering = ['-c_time']
        verbose_name = "电机信息"
        verbose_name_plural = "电机信息"

    def __str__(self):
        if self.comment:
            return self.motor_PN + ' ' + self.motor_model + ' ' + \
                self.motor_code+' | Remark: ' + self.comment
        else:
            return self.motor_PN + ' ' + self.motor_model + ' ' + self.motor_code


class HighSpeed(models.Model):
    motor_PN = models.CharField(max_length=32)
    motor_model = models.CharField(max_length=32)
    motor_code = models.CharField(max_length=32)
    speed = models.IntegerField()
    run_time = models.DurationField()
    forward_direction_list = (('Positive', '正转'),
                              ('Negitive', '反转'),
                              )
    rotate_direction = models.CharField(
        max_length=32, choices=forward_direction_list)
    RTD1_start_temperature = models.FloatField()
    RTD2_start_temperature = models.FloatField()
    RTD1_end_temperature = models.FloatField()
    RTD2_end_temperature = models.FloatField()
    cooling_temperature = models.FloatField()
    cooling_flow = models.FloatField()
    passornot = models.BooleanField()
    comment = models.CharField(max_length=128, null=True, blank=True)
    c_time = models.DateTimeField(auto_now_add=True)
    modify_time = models.DateTimeField(auto_now=True)
    motorinfo = models.ForeignKey(MotorInfo,on_delete=models.CASCADE)

    class Meta:
        ordering = ['-c_time']
        verbose_name = "高转速试验"
        verbose_name_plural = "高转速试验"

    def __str__(self):
        if self.comment:
            return self.motor_PN + ' ' + self.motor_model + ' ' + \
                self.motor_code +' ' +str(self.speed) + ' | Remark: ' + self.comment
        else:
            return self.motor_PN + ' ' + self.motor_model + ' ' + self.motor_code\
             + ' ' + str(self.speed)


class CurrentVsTorque(models.Model):
    motor_PN = models.CharField(max_length=32)
    motor_model = models.CharField(max_length=32)
    motor_code = models.CharField(max_length=32)
    speed_point = models.IntegerField()
    current_target = models.IntegerField(null=True)
    forward_direction_list = (('Positive', '正转'),
                              ('Negitive', '反转'),
                              )
    rotate_direction = models.CharField(
        max_length=32, choices=forward_direction_list)
    control_mode_list = (('Traction_Torque', '扭矩模式_主转'),
                         ('Traction_Speed', '转速模式_主转'),
                         ('Generation_Torque', '扭矩模式_跟转'),
                         ('Generation_Speed', '转速模式_跟转'),
                         )
    control_mode = models.CharField(max_length=32, choices=control_mode_list)
    cooling_type_list = (('Liquid cooling', '冷却液'),
                         ('Air Cooling', '风冷'),
                         )
    cooling_type = models.CharField(max_length=32, choices=cooling_type_list)
    cooling_flow = models.FloatField()
    cooling_temperature = models.FloatField()
    winding_temperature_min = models.FloatField()
    winding_temperature_max = models.FloatField()
    dc_bus_voltage = models.IntegerField()
    temperature_measured = models.FloatField(null=True)
    phase_current_measured = models.FloatField(null=True)
    torque_command = models.FloatField(null=True)
    torque_measured = models.FloatField(null=True)
    Kt = models.FloatField(null=True)
    Ke = models.FloatField(null=True)
    comment = models.CharField(max_length=128, null=True, blank=True)
    c_time = models.DateTimeField(auto_now_add=True)
    modify_time = models.DateTimeField(auto_now=True)
    motorinfo = models.ForeignKey(MotorInfo,on_delete=models.CASCADE)

    class Meta:
        ordering = ['-c_time']
        verbose_name = "电特性试验"
        verbose_name_plural = "电特性试验"

    def __str__(self):
        if self.comment:
            return self.motor_PN + ' ' + self.motor_model + ' ' + \
                self.motor_code +' ' +str(self.speed_point) + ' | Remark: ' + self.comment
        else:
            return self.motor_PN + ' ' + self.motor_model + ' ' + self.motor_code\
             + ' ' + str(self.speed_point)

class ShortCircuit(models.Model):
    motor_PN = models.CharField(max_length=32)
    motor_model = models.CharField(max_length=32)
    motor_code = models.CharField(max_length=32)
    speed_point = models.IntegerField()
    cooling_temperature = models.FloatField()
    winding_temperature_min = models.FloatField()
    winding_temperature_max = models.FloatField()
    env_temperature = models.FloatField()
    env_humidity = models.FloatField()
    forward_direction_list = (('Positive', '正转'),
                              ('Negitive', '反转'),
                              )
    rotate_direction = models.CharField(
        max_length=32, choices=forward_direction_list)
    u_phase_current = models.FloatField()
    v_phase_current = models.FloatField()
    w_phase_current = models.FloatField()
    average_phase_current = models.FloatField()
    u_phase_f_current = models.FloatField()
    v_phase_f_current = models.FloatField()
    w_phase_f_current = models.FloatField()
    average_phase_f_current = models.FloatField()
    torque_measured = models.FloatField()
    temperature_measured = models.FloatField()
    comment = models.CharField(max_length=128, null=True, blank=True)
    c_time = models.DateTimeField(auto_now_add=True)
    modify_time = models.DateTimeField(auto_now=True)
    motorinfo = models.ForeignKey(MotorInfo,on_delete=models.CASCADE)

    class Meta:
        ordering = ['-c_time']
        verbose_name = "短路试验"
        verbose_name_plural = "短路试验"

    def __str__(self):
        if self.comment:
            return self.motor_PN + ' ' + self.motor_model + ' ' + \
                self.motor_code +' ' +str(self.speed_point) + ' | Remark: ' + self.comment
        else:
            return self.motor_PN + ' ' + self.motor_model + ' ' + self.motor_code\
             + ' ' + str(self.speed_point)

class Insulation(models.Model):
    motor_PN = models.CharField(max_length=32)
    motor_model = models.CharField(max_length=32)
    motor_code = models.CharField(max_length=32)
    resistance_15s = models.FloatField()
    resistance_60s = models.FloatField()
    temperature_measured = models.FloatField()
    rtd1 = models.FloatField()
    rtd2 = models.FloatField()
    room_temperature = models.FloatField()
    room_humidity = models.FloatField()
    winding_phase_u_v = models.FloatField()
    winding_phase_v_w = models.FloatField()
    winding_phase_u_w = models.FloatField()
    insulation_voltage = models.IntegerField()
    insulation_resistance = models.FloatField()
    hipot_voltage = models.IntegerField()
    hipot_resistance= models.FloatField()
    recorder = models.CharField(max_length=32,null = True,blank = True)
    comment = models.CharField(max_length=128, null=True, blank=True)
    c_time = models.DateTimeField(auto_now_add=True)
    modify_time = models.DateTimeField(auto_now=True)
    motorinfo = models.ForeignKey(MotorInfo,on_delete=models.CASCADE)

    class Meta:
        ordering = ['-c_time']
        verbose_name = "绝缘测试"
        verbose_name_plural = "绝缘测试"

    def __str__(self):
        if self.comment:
            return self.motor_PN + ' ' + self.motor_model + ' ' + \
                self.motor_code+' | Remark: ' + self.comment
        else:
            return self.motor_PN + ' ' + self.motor_model + ' ' + self.motor_code

class Continuous(models.Model):
    motor_PN = models.CharField(max_length=32)
    motor_model = models.CharField(max_length=32)
    motor_code = models.CharField(max_length=32)
    control_mode_list = (('Traction_Torque', '扭矩模式_主转'),
                     ('Traction_Speed', '转速模式_主转'),

test_app/templates/test_app/DataView.html
{% extends "test_app/base.html" %}
{% load staticfiles %}
{% block title %}
    高速试验
{% endblock title %}
{% block css %}
    
{% endblock css %}
{% block content %}
    

<body>
    <table class="table table-responsive-sm">
        <caption>电机基本信息 ↑</caption>
        <thead>
            <tr>
                <th colspan="" rowspan="" headers="" scope="">电机零件号</th>
                <th colspan="" rowspan="" headers="" scope="">电机型号</th>
                <th colspan="" rowspan="" headers="" scope="">电机编码</th>
                <th colspan="" rowspan="" headers="" scope="">三相相序</th>
                <th colspan="" rowspan="" headers="" scope="">正转方向</th>
                <th colspan="" rowspan="" headers="" scope="">逆变器型号</th>
                <th colspan="" rowspan="" headers="" scope="">逆变器序列号</th>
                <th colspan="" rowspan="" headers="" scope="">逆变器EEPROM</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td colspan="" rowspan="" headers="">{{motorinfoobj.motor_PN}}</td>
                <td colspan="" rowspan="" headers="">{{motorinfoobj.motor_model}}</td>
                <td colspan="" rowspan="" headers="">{{motorinfoobj.motor_code}}</td>
                <td colspan="" rowspan="" headers="">{{motorinfoobj.phase_connection}}</td>
                <td colspan="" rowspan="" headers="">{{motorinfoobj.get_forward_direction_display}}</td>
                <td colspan="" rowspan="" headers="">{{motorinfoobj.get_inverter_type_display}}</td>
                <td colspan="" rowspan="" headers="">{{motorinfoobj.inverter_serial}}</td>
                <td colspan="" rowspan="" headers="">{{motorinfoobj.motor_type_options_eeprom}}</td>
            </tr>
        <thead>
            <tr>
                <th colspan="" rowspan="" headers="" scope="">测试人员 1</th>
                <th colspan="" rowspan="" headers="" scope="">测试人员 2</th>
                <th colspan="" rowspan="" headers="" scope="">环境温度</th>
                <th colspan="" rowspan="" headers="" scope="">环境湿度</th>
                <th colspan="" rowspan="" headers="" scope="">电机极数</th>
                <th colspan="" rowspan="" headers="" scope="">旋变极数</th>
                <th colspan="" rowspan="" headers="" scope="">记录时间</th>
                <th colspan="" rowspan="" headers="" scope="">修改时间</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td colspan="" rowspan="" headers="">{{motorinfoobj.get_tester1_display}}</td>
                <td colspan="" rowspan="" headers="">{{motorinfoobj.get_tester2_display}}</td>
                <td colspan="" rowspan="" headers="">{{motorinfoobj.ambient_temperature}}</td>
                <td colspan="" rowspan="" headers="">{{motorinfoobj.ambient_humidity}}</td>
                <td colspan="" rowspan="" headers="">{{motorinfoobj.motor_poles}}</td>
                <td colspan="" rowspan="" headers="">{{motorinfoobj.resolver_poles}}</td>
                <td colspan="" rowspan="" headers="">{{motorinfoobj.c_time}}</td>
                <td colspan="" rowspan="" headers="">{{motorinfoobj.modify_time}}</td>
            </tr>
        </tbody>
        <thead>
            <tr>
                <th colspan="8" rowspan="" headers="" scope="">备注</th>
            </tr>
        </thead>
        <tbody>
            <tr>
               <td colspan="8" rowspan="" headers="">{{motorinfoobj.comment}}</td>
            </tr>
        </tbody>
    </table>


{% if motorhighspeedobj_list %}
    <table class="table table-hover table-responsive-sm">
        <caption>高转速试验结果 ↑</caption>
        <thead>
            <tr>
                <th colspan="" rowspan="" headers="" scope="">转速</th>
                <th colspan="" rowspan="" headers="" scope="">运行时长</th>
                <th colspan="" rowspan="" headers="" scope="">运转方向</th>
                <th colspan="" rowspan="" headers="" scope="">RTD1开始温度</th>
                <th colspan="" rowspan="" headers="" scope="">RTD2开始温度</th>
                <th colspan="" rowspan="" headers="" scope="">RTD1结束温度</th>
                <th colspan="" rowspan="" headers="" scope="">RTD2结束温度</th>
                <th colspan="" rowspan="" headers="" scope="">冷却温度</th>
                <th colspan="" rowspan="" headers="" scope="">是否通过</th>
                <th colspan="" rowspan="" headers="" scope="">创建时间</th>
                <th colspan="" rowspan="" headers="" scope="">修改时间</th>
                <th colspan="" rowspan="" headers="" scope="">备注</th>
            </tr>
        </thead>

        <tbody>
            {% for motorhighspeedobj in motorhighspeedobj_list %}
            <tr>
                <td colspan="" rowspan="" headers="">{{motorhighspeedobj.speed}}</td>
                <td colspan="" rowspan="" headers="">{{motorhighspeedobj.run_time}}</td>
                <td colspan="" rowspan="" headers="">{{motorhighspeedobj.get_rotate_direction_display}}</td>
                <td colspan="" rowspan="" headers="">{{motorhighspeedobj.RTD1_start_temperature}}</td>
                <td colspan="" rowspan="" headers="">{{motorhighspeedobj.RTD2_start_temperature}}</td>
                <td colspan="" rowspan="" headers="">{{motorhighspeedobj.RTD1_end_temperature}}</td>
                <td colspan="" rowspan="" headers="">{{motorhighspeedobj.RTD2_end_temperature}}</td>
                <td colspan="" rowspan="" headers="">{{motorhighspeedobj.cooling_temperature}}</td>
                <td colspan="" rowspan="" headers="">{{motorhighspeedobj.passornot}}</td>
                <td colspan="" rowspan="" headers="">{{motorhighspeedobj.c_time}}</td>
                <td colspan="" rowspan="" headers="">{{motorhighspeedobj.modify_time}}</td>
                <td colspan="" rowspan="" headers="">{{motorhighspeedobj.comment}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endif %}

</body>
{% endblock content %}

test_app/templates/test_app/base.html
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>{% block title %}base{% endblock %}</title>

    <!-- Bootstrap -->
    {% load staticfiles %}
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel= "SHORTCUT ICON" href="{% static 'img/favicon.ico' %}">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block css %}{% endblock %}
  </head>
  <body>
    <nav class="navbar navbar-expand-sm bg-secondary navbar-dark">
      <button class="navbar-toggler" type="button" data-toggle="collapse" 
      data-target="#collapsibleNavbar2"><span class="navbar-toggler-icon"></span>
      </button>
      <a class ="navbar-brand" href="{% url 'login_app:index' %}" title="磁雷革传动">MAGELEC <small>信息管理系统</small></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" 
      data-target="#collapsibleNavbar"><span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="collapsibleNavbar">
      <ul class ="navbar-nav">
        {% if user.name %}
        <li class="navbar-text"><a class="nav-link" href= "#">{{ user.name }}</a></li>
        <li class="navbar-text"><a class="nav-link" href= "{% url 'login_app:logout' %}">登出</a></li>
        {% else %}
        <li class="navbar-text"><a class="nav-link" href= "{% url 'login_app:login' %}">登录</a></li>   
        <li class="navbar-text"><a class="nav-link" href= "{% url 'login_app:register' %}">注册</a></li>     
        {% endif %}
      </ul>
      </div>
    </nav>
    <div class="row flex-sm-row">
    <div class="col-sm-2 bg-white navbar-expand-sm">
      <nav class="nav-tabs text-sm-left">
      <div class="collapse navbar-collapse" id="collapsibleNavbar2">
        <ul class="list-group">
          <li><a class="nav-link text-secondary" href="{% url 'test_app:index' %}">首页</a></li>
          <li><a class="nav-link text-secondary" href="{% url 'test_app:basic' %}">基础信息</a></li>
          <li><a class="nav-link text-secondary" href="{% url 'test_app:insulation' %}">绝缘性测量</a></li>
          <li><a class="nav-link text-secondary" href="{% url 'test_app:bemf' %}">反电动势测量</a></li>
          <li><a class="nav-link text-secondary" href="{% url 'test_app:shortcircuit' %}">短路试验</a></li>
          <li><a class="nav-link text-secondary" href="{% url 'test_app:calibrate' %}">逆变器标定</a></li>
          <li><a class="nav-link text-secondary" href="{% url 'test_app:currentvstorque' %}">电特性试验</a></li>
          <li><a class="nav-link text-secondary" href="{% url 'test_app:continuous' %}">连续扭矩试验</a></li>
          <li><a class="nav-link text-secondary" href="{% url 'test_app:highspeed' %}">高转速试验</a></li>
          <li><a class="nav-link text-secondary" href="{% url 'test_app:efficiency' %}">效率试验</a></li>
          <li><a class="nav-link text-secondary" href="{% url 'test_app:dataview' %}">结果预览</a></li>
          <li><a class="nav-link text-secondary" href="{% url 'test_app:search' %}">电机查询</a></li>
        </ul>
      </div>
      </nav>
      <a class="text-muted text-right nav-link" href="mailto:syu@magelec.cn?subject=feedback" "email me">Contact Me !</a>
    </div>
    <div class="col-sm-10">
    <div class="container-fluid">
      <div class="list-group text-right">
      {% if motorinfoobj %}
        <a class="text-muted" href="{% url 'test_app:motor_logout' %}"> 切换电机 </a>
        <a class="text-muted" href="#">{{motorinfoobj}}</a>
      {% else %}
        <a class="text-muted offset-sm-11" href="{% url 'test_app:search' %}" title=""> 查询电机 </a>
      {% endif %}
      </div>
      {% block content %}{% endblock %}
    </div>
    </div>
    </div>

    <p class="text-muted text-sm-center">&copy; 2017-2019 <br><a class="text-muted text-sm-center" href="http://www.magelec.cn/home" title="">www.magelec.cn</a></p>
    
    
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{% static 'js/jquery-3.4.1.js' %}"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>

test_app/templates/test_app/calibrate.html
{% extends "test_app/base.html" %}
{% load staticfiles %}
{% block title %}
    标定流程
{% endblock title %}
{% block css %}
    
{% endblock css %}

{% block content %}
<div>
    <div class="container-fluid">
    <h1 class="h3 text-center">标定流程</h1>
    <form  action="{% url 'test_app:calibrate' %}" method="post" accept-charset="utf-8">
        {% csrf_token %}
        <table class="table table-responsive-sm table-hover">
            <thead class="thead-dark">
                <tr>
                    <th>Stator_Resistance_EEPROM_x10000</th>
                    <th>Veh_Flux_EEPROM(WB)_x1000</th>
                    <th>Ld_Lq_Const_EEPROM(uH)</th>
                    <th colspan="" rowspan="" headers="" scope="">备注</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td colspan="" rowspan="" headers="">{{winding_average}}</td>
                    <td colspan="" rowspan="" headers="">{{veh_flux}}</td>
                    <td colspan="" rowspan="" headers="">{{Ld_Lq_Const}}</td>
                </tr>
                <tr >
                    <td > <input class="form-control-plaintext" type="number" name="Stator_Resistance_EEPROM_x10000" min="0" required></td>
                    </select> </td>
                    <td > <input class="form-control-plaintext" type="number" name="Veh_Flux_EEPROM_x1000" min="0" required> </td>
                    <td > <input class="form-control-plaintext" type="number" name="Ld_Lq_Const_EEPROM" min="0" required> </td>
                    <td > <input class="form-control-plaintext" type="text" name="comment"> </td>
                </tr> 
            </tbody>
        <table class="table table-responsive-sm table-hover">
            <thead class="thead-dark">
                <tr>
                    <th>Kp_Current_EEPROM_x1000</th>
                    <th>Ki_Current_EEPROM_x10000</th>
                    <th>Gamma_Adjust_(Deg)x10</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td colspan="" rowspan="" headers="">{{Kp_Current}}</td>
                    <td colspan="" rowspan="" headers="">{{Ki_Current}}</td>
                    <td colspan="" rowspan="" headers=""><a class="text-secondary" href="{% url 'test_app:gamma' %}">计算GAMMA角</a></td>
                </tr>
                <tr >
                    <td > <input class="form-control-plaintext" type="number" name="Kp_Current_EEPROM_x1000" min="0" required></td>
                    <td > <input class="form-control-plaintext" type="number" name="Ki_Current_EEPROM_x10000" min="0" required> </td>
                    <td > <input class="form-control-plaintext" type="number" name="Gamma_Adjust_x10" required> </td>
                </tr> 
            </tbody>
        </table>
            <div class="flex-sm-row offset-sm-11">
                <button type="submit" class="btn btn-primary" value="submit">提交</button>
            </div>
    </form>
    </div>
    <p class="col-sm-auto"> 第一行为通过计算所得应设置值，第二行为实际设置值!</p>
</div>
{% endblock content %}

test_app/templates/test_app/efficiency.html
{% extends "test_app/base.html" %}
{% load staticfiles %}
{% block title %}
    效率测试-敬请期待
{% endblock title %}
{% block css %}
    
{% endblock css %}

{% block content %}
    <body class="text-center">
    <P> 未开放，敬请期待！</P>
    </body>
{% endblock content %}

test_app/templates/test_app/index.html
{% extends "test_app/base.html" %}
{% load staticfiles %}
{% block title %}
    首页
{% endblock title %}
{% block css %}
    
{% endblock css %}

{% block content %}
    <body class="text-center">
    <P> <b>Welcome!</b><br>nice to see you !<br>{{user.name}}--欢迎您回来！</P>
    </body>
{% endblock content %}

test_app/templates/test_app/search.html
{% extends "test_app/base.html" %}
{% load staticfiles %}
{% block title %}
    数据查询
{% endblock title %}
{% block css %}
    
{% endblock css %}

{% block content %}
<div class="container">
    <form action="{% url 'test_app:search' %}"  method="POST" accept-charset="utf-8">
        {% csrf_token %}
        <div class="text-sm-center">
            <label class="text-muted">电机零件号 | PN<input class="form-control" type="search" name="motor_PN_search" value=""></label>
            <label class="text-muted">电机型号 | Model<input class="form-control" type="search" name="motor_model_search" value=""></label>
            <label class="text-muted">电机编码 | Code<input class="form-control" type="search" name="motor_code_search" value=""></label>
        </div>
        <br>
        <div class="text-sm-center">
            <button class="btn btn-lg btn-primary" type="submit">查找</button>
        </div>
    </form>
    <br>
    <form action= "{% url 'test_app:motor_login' %}" method="POST" accept-charset="utf-8">
        {% csrf_token %}
    <div class="container">
    {% for motorinfoobj in motorinfoobj_list %}
        <button class="btn" type="submit" name="motorindex" value="{{motorinfoobj.id}}">{{motorinfoobj}}</button>
    {% endfor %}
    </div>
    </form>
</div>

{% endblock content %}